name: Request Preview Deploy

on:
  push:
    branches:
      - feature/endorsing-artists

permissions:
  contents: read
  actions: write

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger preview deployment on main
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: deploy-preview
